services:

  postgres:
    image: postgres:16-alpine
    container_name: cep-postgres
    network_mode: "host"
    environment:
      POSTGRES_DB: cep_rules
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: cep-api
    network_mode: "host"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/cep_rules
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres-data: