FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests
RUN cd target && jar -xf cep-dynamic-1.0-SNAPSHOT.jar

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=builder /app/target/BOOT-INF/lib /app/lib
COPY --from=builder /app/target/BOOT-INF/classes /app/classes

CMD ["java", "-cp", "/app/classes:/app/lib/*", "gemoc.mbdo.cep.engine.CepEngineApplication"]